fix download files in datasets that have absolute url
ONSdigital/dp-api-clients-go pull request #121
Opened 2021-06-18 11:47 UTC by s-xton

### What

Fixed an issue where an absolute url for a download file in data.json was still appended onto the page url: 

### How to review

Check against existing content. If you are reviewing pls contact me for a URL with an absolute path

### Who can review

Anyone with sufficient knowledge of this repo

2021-06-18 13:31 UTC, ChrysmOre submitted a review, later dismissed

2021-06-18 14:26 UTC, nshumoogum submitted a review, later dismissed
Nice spot

2021-07-01 14:39 UTC, nshumoogum requested changes

2021-07-01 14:39 UTC, nshumoogum commented on ci/lint.yml
> +  - name: dp-dataset-api
I believe this be `dp-api-clients-go`

2021-07-01 14:43 UTC, nshumoogum commented on ci/lint.yml
> +  - name: dp-dataset-api
Also wondering whether it is worth upgrading library to use latest go version - i think it is now on 1.16.5

2021-07-01 14:44 UTC, nshumoogum approved these changes

2021-07-01 14:50 UTC, merged