Feature/batch processing
ONSdigital/dp-api-clients-go pull request #84
Opened 2020-12-31 13:00 UTC by DavidSubiros

### What

Copied batch processing functions from dp-frontend-filter-datase-controller, we need at least a function to get items in batches, and a function to process each batch. This has been generalised into `ProcessInConcurrentBatches`

- Implemented generic concurrent batch processing in common.go:
  - executes up to `MaxWorkers` parallel calls
  - after the first call, the total count is determined, and further batches are executed in parallel, if required
  - if a `getter` returns an error, the operation is aborted (no more batches are requested)
  - if a `processor` returns an error or forces to abort then the operation is aborted (no more batches are requested)
 
- Implemented specific usages of the concurrent batch processing for filter GetDimensionOptions:
  - GetDimensionOptionsInBatches aggregates teh batches and returns the full list of items
  - GetDimensionOptionsBatchProcess executes the provided batch processor for each batch (more efficient)

- Added unit tests for generic batch processing and filter client batch processing

### How to review

- Make sure changes make sense
- Make sure unit tests pass

### Who can review

Anyone

2021-01-11 10:00 UTC, CarlHembrough requested changes
Looks good overall - I like the generic batch processing. I have added some points to check 👍

2021-01-11 11:50 UTC, DavidSubiros commented on common/batch.go
> +		lockResult.Unlock()
good point

2021-01-11 12:00 UTC, DavidSubiros commented on dataset/dataset.go
> +			opts.Items = make([]Option, batch.TotalCount)
`GetOptionsInBatches` gets all the options by aggregating the paginated responses from dataset api. In this line, we initialise the full struct that will contain all the items, adding a comment in the code to make it clearer:
```
// Function to aggregate items.
// For the first received batch, as we have the total count information, will initialise the final structure of items with a fixed size equal to TotalCount.
// This serves two purposes:
//   - We can guarantee, even with concurrent calls, that values are returned in the same order that the API defines, by offsetting the index.
//   - We do a single memory allocation for the final array, making the code more memory efficient.
```

2021-01-11 12:01 UTC, DavidSubiros commented on dataset/dataset.go
> +			opts.Items = make([]Option, batch.TotalCount)
Please, let me know if the comment is not clear

2021-01-11 12:02 UTC, DavidSubiros commented on dataset/dataset.go
> +			opts.Count = batch.TotalCount
Same as above, this corresponds to the count for the struct that will contain all the items.

2021-01-11 12:04 UTC, DavidSubiros commented on filter/filter.go
> +			opts.Count = batch.TotalCount
Added same comment

2021-01-11 12:14 UTC, CarlHembrough commented on dataset/dataset.go
> +			opts.Items = make([]Option, batch.TotalCount)
I see - apologies, this was me misreading the code 👍

2021-01-12 09:39 UTC, CarlHembrough approved these changes
👍

2021-01-12 09:44 UTC, merged